# Basic Information 
title: S M Taslim Uddin Raju
position_1: AI Researcher  
position_2: MASc in ECE (Specialized in  
  <a href="https://uwaterloo.ca/electrical-computer-engineering/pattern-analysis-and-machine-intelligence-pami" target="_blank">AI</a>)
affiliation: University of Waterloo
affiliation_link: https://uwaterloo.ca/
affiliation_logo: /assets/img/logo.png
email: smturaju@uwaterloo.ca

# Search Engine Optimization (SEO)
keywords: S M Taslim Uddin Raju, Raju S M Taslim Uddin, smturaju
canonical: https://priscilla100.github.io
# description: S M Taslim Uddin Raju 

# The option is used to enable the Illinois template.
enable_hopkins_logo: true

# The option is used to show the last update time.
enable_last_update: false

# Links
link_type: icon #text/icon
google_scholar: https://scholar.google.ca/citations?user=ToadRS8AAAAJ&hl=en
github_link: https://github.com/raju32742
linkedin: https://www.linkedin.com/in/raju32742/
twitter: https://x.com/RauUddin
email: smturaju@uwaterloo.ca

# Images 
avatar: /assets/img/me.jpg

# Footnotes
# footnote: Feel free to use my website's source code.
# footnote_link: https://github.com/yaoyao-liu/minimal-light

# Analytics
# Please remove the following lines about analytics services if you fork my project. 
# Otherwise, the analytics information of your website will be recorded to my ClustrMaps accounts.
# clustrmaps_id: CJD8XwsJhSyQ6sbsU-Gw0cNcUlbah7KW3xvHN2QlwW0

# The following files will be removed from the generated website.
exclude:
  - build.sh
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - CNAME
